import type { Metadata } from "next";
import Navbar from "@/components/Navbar";
import localFont from "next/font/local";
//import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import { Container } from "react-bootstrap";

import '../styles/globals.scss';


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{
          background: "linear-gradient(to left, #040404, #110730)",
          minHeight: "100vh",
        }}
      >
        <Container>
          <Navbar />
        </Container>

        <main>
          <Container>{children}</Container>
        </main>
      </body>
    </html>
  );
}
